export const portugueseLocations = [
  'Lisboa, Portugal',
  'Porto, Portugal',
  'Braga, Portugal',
  'Coimbra, Portugal',
  'Faro, Portugal',
  'Setubal, Portugal',
  'Leiria, Portugal',
  'Aveiro, Portugal',
  'Viseu, Portugal',
  'Guimaraes, Portugal',
  'Funchal, Madeira',
  'Ponta Delgada, Acores',
  'Londres, Reino Unido',
  'Paris, Franca',
  'Berlim, Alemanha',
  'Madrid, Espanha',
  'Amsterdam, Holanda',
  'Nova York, EUA',
  'Sao Paulo, Brasil',
  'Luanda, Angola',
];
